import { use, useState } from 'react';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import io from 'socket.io-client';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import { setUsername, setRoom } from './store/reducers/userSlice';

const inter = Inter({ subsets: ['latin'] })
export const socket = io.connect("http://localhost:3002")

export default function Home() {
  
  const user = useSelector(state => state.user.username)
  const room = useSelector(state => state.user.room)
  const dispatch = useDispatch()
  const router = useRouter()

  const joinRoom = () => {
    if (user !== ' ' && room !== ' '){
      socket.emit("join_room", room)
      router.push('/components/Chat')
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>Join Chat</h3>
        <Form.Control type='text' placeholder='John...' onChange={(e) => {dispatch(setUsername(e.target.value))}}></Form.Control>
        <Form.Control type='text' placeholder='Room ID...' onChange={(e) => {dispatch(setRoom(e.target.value))}}></Form.Control>
        <Button onClick={joinRoom}>Join the room</Button>
      </main>
    </>
  )
}
